### ISSUE TITLE
Issue with chapters and letters: FRA00801

### ISSUE THREAD

**Issue by christofs** [COST-ELTeC/ELTeC-fra#10]
There are some brief letters in there encoded as "div" at the same level as chapters. Not sure this is the best way. Maybe use "quote"?

**Comment by lb42** [comment]
If the letter is presented as part of the chapter (which is clearly the case for at least the first of these: "elle la saisit vivement, en brisa le cachet et lut ce qui suit:"  does not sound like the end of a chapter) then it should definitely be `<quote>` rather than `<div>` . Use `<div type=letter>` ONLY for the case where the whole novel is organised as a sequence of letters.

**Comment by christofs** [comment]
Agreed, thanks for the clarification.
